[package]
name = "wasm-synth"
version = "0.5.0"
edition = "2021"

[dependencies.parity-wasm]
git = "https://github.com/paritytech/parity-wasm.git"
features = ["multi_value", "sign_ext"]

[dependencies.codegen-luajit]
path = "../codegen-luajit"

[dependencies.codegen-luau]
path = "../codegen-luau"
